server:
  name: Go_REST
  host: "0.0.0.0"
  port: "8989"
  writetimeout: 15
  readtimeout: 15
 
logger:
  writetofile: false
  format: text

  
database:
    server: "127.0.0.1"
    port: 5432
    user: "postgres"
    password: "12345"
    database: "mydb"
    sslmode: disable
    migration: true